
CREATE TABLE IF NOT EXISTS "events" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "aggregate_name" character varying(50) NOT NULL,
    "aggregate_id" character varying(50) NOT NULL,
    "event_num" integer NOT NULL,
    "data" character varying NOT NULL,
    CONSTRAINT "events_unique" UNIQUE ("aggregate_name", "aggregate_id", "event_num")
);


CREATE TABLE IF NOT EXISTS "readmodel_boards" (
    "card_id" character varying PRIMARY KEY,
    "title" character varying,
    "description" character varying,
    "status" character varying 
);
