version: '3.1'

services:

  db:
    image: postgres
    restart: no
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql